Repository atlp-rwanda/Avengers-Phantom-FE, pull requests merged in 2022-06, with the labels that each got.

#40 Ft simulate the bus motion
  .DS_Store
  .dockerignore
  Dockerfile
  README.md
  node_modules/react-router-dom/package.json
  package-lock.json
  package.json
  src/.DS_Store
  src/App.css
  src/App.js
  src/Assets/bus.png
  src/Assets/carBreak.mp3
  src/Assets/carsound.mp3
  src/Assets/carstart.mp3
  src/Assets/marker.png
  src/Assets/movingcar.mp3
  src/Assets/output.gif
  src/Assets/phantomIconCar.png
  src/Components/Homepage/MapSection.jsx
  src/Components/Homepage/ScrollToTop.jsx
  src/Components/Simulation/CarMarker.js
  src/Components/Simulation/LocationMaker.js
  src/Components/Simulation/MovingMarker.js
  src/Components/Simulation/RoutingControl.js
  src/Components/Simulation/Simulation.js
  src/Components/Simulation/SpeedMeter.js
  src/Components/Simulation/simulation.css
  src/Components/dashboard/buses/BusDetail.jsx
  src/Components/dashboard/buses/BusSkeleton.jsx
  src/Components/dashboard/buses/BusesList.jsx
  src/Components/dashboard/buses/RegisterBus.jsx
  src/Components/dashboard/buses/updateBus.jsx
  src/Components/dashboard/operatorsanddriver/AddDrivers.jsx
  src/Components/dashboard/operatorsanddriver/AddOperator.jsx
  src/Components/dashboard/operatorsanddriver/CardSkeleton.jsx
  src/Components/dashboard/operatorsanddriver/DriverAndOperator.jsx
  src/Components/dashboard/route/AddRouteInit.jsx
  src/Components/dashboard/route/AddRoutes.jsx
  src/Components/dashboard/route/RoutesReport.jsx
  src/Components/dashboard/route/SingleRoutes.jsx
  src/Components/dashboard/updateProfile/updateProfile.jsx
  src/Layouts/Dashboard.js
  src/Layouts/SideBar.js
  src/Layouts/styles.js
  src/Simulator/script.js
  src/index.html
  src/routes/route.js
  webpack.config.js
Labels: wip, waiting for reviews

#39 Ft(update-profile): Update user profile
  .gitignore
  node_modules/react-router-dom/package.json
  package-lock.json
  package.json
  server.js
  src/Components/dashboard/operatorsanddriver/Drivers.jsx
  src/Components/dashboard/updateProfile/Skeletons/Skeleton.css
  src/Components/dashboard/updateProfile/Skeletons/SkeletonElement.jsx
  src/Components/dashboard/updateProfile/changePassword.jsx
  src/Components/dashboard/updateProfile/index.js
  src/Components/dashboard/updateProfile/style.css
  src/Components/dashboard/updateProfile/updateProfile.jsx
  src/Components/dashboard/updateProfile/viewProfile.jsx
  src/Components/signin/Signin.jsx
  src/redux/Action/actiontypes.js
  src/redux/Action/fetchUserData.js
  src/redux/Reducer/fetchUserData.js
  src/redux/Reducer/index.js
  src/routes/route.js
Labels: wip, waiting for reviews

#44 Ft crud operations buses
  node_modules/react-router-dom/package.json
  package-lock.json
  server.js
  src/Components/dashboard/buses/BusDetail.jsx
  src/Components/dashboard/buses/BusesList.jsx
  src/Components/dashboard/buses/RegisterBus.jsx
  src/Components/dashboard/buses/Validations.jsx
  src/Components/dashboard/buses/skeletons/SkeletonElement.jsx
  src/Components/dashboard/buses/updateBus.jsx
  src/Components/signin/Signin.jsx
  src/Layouts/SideBar.js
  src/example.env
  src/redux/Action/actiontypes.js
  src/redux/Action/fetchallbuses.js
  src/redux/Reducer/fetchallbuses.js
  src/routes/route.js
  webpack.config.js
Labels: wip

#45 feat(roles):roles integration
  example.env
  package-lock.json
  src/Components/Homepage/ClientMap.js
  src/Components/Homepage/RoutingControl.js
  src/Components/Homepage/carMarker.js
  src/Components/Simulation/CalculateTime.js
  src/Components/dashboard/Dashboard.css
  src/Components/dashboard/roles&permission/CreateRole.js
  src/Components/dashboard/roles&permission/RoleList.js
  src/Components/dashboard/roles&permission/Roles.jsx
  src/Components/dashboard/roles&permission/Skeleton.js
  src/Components/dashboard/roles&permission/role.css
  src/Components/dashboard/route/Skeletons/SingleSkeleton.jsx
  src/Components/dashboard/route/Skeletons/Skeleton.css
  src/Components/dashboard/route/Skeletons/SkeletonElement.jsx
  src/Components/dashboard/route/UpdateRoute.css
  src/Components/dashboard/route/UpdateRouteButton.jsx
  src/Components/dashboard/route/pagination.jsx
  src/Components/dashboard/updateProfile/Skeletons/Skeleton.css
  src/Components/dashboard/updateProfile/changePassword.jsx
  src/Components/dashboard/updateProfile/index.js
  src/Components/dashboard/updateProfile/viewProfile.jsx
  src/Components/signin/Signin.jsx
  src/Layouts/ClientDashoard.js
  src/Layouts/Dashboard.js
  src/Layouts/SideBar.js
  src/Layouts/styles.js
  src/api/index.js
  src/redux/Action/RoleActions.js
  src/redux/Action/actiontypes.js
  src/redux/Action/fetchUserData.js
  src/redux/Action/routes.js
  src/redux/Reducer/GetRoleReducer.js
  src/redux/Reducer/RoleReducers.js
  src/redux/Reducer/createRoleReducer.js
  src/redux/Reducer/deleteRoleReducer.js
  src/redux/Reducer/fetchUserData.js
  src/redux/Reducer/getAllRolesReducer.js
  src/redux/Reducer/index.js
  src/redux/Reducer/routes.js
  src/redux/Reducer/updateRoleReducer.js
  src/routes/route.js
  src/utils/sokect.js
Labels: waiting for reviews, Done
