Repository atlp-rwanda/Avengers-Phantom-FE, pull requests merged in 2022-07, with the labels that each got.

#51 bg-fixing-routes-crud-2
  src/Components/dashboard/route/AddRouteInit.jsx
  src/Components/dashboard/route/RoutesReport.jsx
  src/Components/dashboard/route/SingleRoutes.jsx
  src/Components/dashboard/route/UpdateRouteButton.jsx
  src/redux/Action/routes.js
Labels: bug, Done

#52 fixed login form
  package-lock.json
  package.json
  procfile
  src/.DS_Store
  src/App.css
  src/Components/.DS_Store
  src/Components/Functions/Function.js
  src/Components/Homepage/About.jsx
  src/Components/Homepage/Contact.jsx
  src/Components/Homepage/Home.jsx
  src/Components/Homepage/Manuals.jsx
  src/Components/Homepage/Services.jsx
  src/Components/Simulation/Simulation.js
  src/Components/dashboard/buses/skeletons/SkeletonElement.jsx
  src/Components/dashboard/route/RoutesReport.jsx
  src/Components/dashboard/route/SingleRoutes.jsx
  src/Components/navbar/Navbar.jsx
  src/Components/signin/Signin.jsx
  src/Components/signin/styles.css
  src/Layouts/Dashboard.js
  src/Layouts/SideBar.js
  src/Layouts/styles.js
  src/example.env
  src/redux/Action/routes.js
  src/routes/privateRoutes.js
  src/routes/route.js
  webpack.config.js
Labels: waiting for reviews, Done

#42 Ch badges integrations
  .coveralls.yml
  .github/workflows/Ci.yml
  README.md
  babel.config.json
  fileTransformer.js
  package-lock.json
  package.json
  src/Components/Homepage/Home.test.js
  src/Components/Homepage/Home_test.js
  src/Components/Homepage/MapSection.jsx
  src/Components/dashboard/route/AddRouteInit.jsx
  src/Components/dashboard/route/AddRoutes.css
  src/Components/dashboard/route/SingleRoutes.jsx
  src/Components/dashboard/route/Skeletons/Skeleton.css
  src/Components/signin/Signin.jsx
  src/Components/yes/yes.js
  src/redux/Action/fetchallbuses.js
  src/test/custom-jest-environment.js
  src/test/setupTests.js
Labels: waiting for reviews, Done

#54 ft-integration-drivers-and-operators
  src/App.css
  src/Components/Functions/Function.js
  src/Components/dashboard/operatorsanddriver/AddDrivers.jsx
  src/Components/dashboard/operatorsanddriver/AddOperator.jsx
  src/Components/dashboard/operatorsanddriver/Drivers.jsx
  src/Components/dashboard/operatorsanddriver/Operators.jsx
  src/Components/dashboard/operatorsanddriver/UpdateOperator.jsx
  src/Components/dashboard/operatorsanddriver/updateDriver.jsx
  src/Components/dashboard/route/SingleRoutes.jsx
  src/Components/dashboard/route/Skeletons/Skeleton.css
  src/Layouts/styles.js
  src/redux/Action/DriversAndOperators/driversAndOperators.js
  src/redux/Action/DriversAndOperators/users_actionsType.js
  src/redux/Action/fetchallbuses.js
  src/redux/Reducer/driversAndOperators.js
  src/redux/Reducer/index.js
  src/routes/route.js
Labels: wip, waiting for reviews

#57 bg(UI):fixing ui designs on dashboard
  .coveralls.yml
  babel.config.json
  fileTransformer.js
  package-lock.json
  src/Components/Homepage/About.jsx
  src/Components/Homepage/Home.jsx
  src/Components/Homepage/Home_test.js
  src/Components/Simulation/CarMarker.js
  src/Components/Simulation/RoutingControl.js
  src/Components/Simulation/Simulation.js
  src/Components/Simulation/SpeedMeter.js
  src/Components/commons/Map.js
  src/Components/dashboard/Dashboard.css
  src/Components/dashboard/buses/BusesList.jsx
  src/Components/dashboard/buses/RegisterBus.jsx
  src/Components/dashboard/buses/style.css
  src/Components/dashboard/operatorsanddriver/AddDrivers.jsx
  src/Components/dashboard/operatorsanddriver/AddOperator.jsx
  src/Components/dashboard/operatorsanddriver/DriverAndOperator.css
  src/Components/dashboard/operatorsanddriver/Drivers.jsx
  src/Components/dashboard/operatorsanddriver/Operators.jsx
  src/Components/dashboard/operatorsanddriver/UpdateOperator.jsx
  src/Components/dashboard/operatorsanddriver/updateDriver.jsx
  src/Components/dashboard/route/AddRouteInit.jsx
  src/Components/dashboard/route/AddRoutes.css
  src/Components/dashboard/route/RoutesReport.jsx
  src/Components/dashboard/route/SingleRoutes.jsx
  src/Components/dashboard/updateProfile/style.css
  src/Components/dashboard/updateProfile/updateProfile.jsx
  src/Components/dashboard/updateProfile/viewProfile.jsx
  src/Components/signin/Signin.jsx
  src/Components/yes/yes.js
  src/Layouts/Dashboard.js
  src/Layouts/SideBar.js
  src/Layouts/styles.js
  src/redux/Action/AssigmentAction.js
  src/redux/Action/DriversAndOperators/driversAndOperators.js
  src/redux/Action/DriversAndOperators/users_actionsType.js
  src/redux/Action/actiontypes.js
  src/redux/Action/driverSimulation.js
  src/redux/Reducer/AllBusAssignment.js
  src/redux/Reducer/assignBusToRoute.js
  src/redux/Reducer/driversAndOperators.js
  src/redux/Reducer/index.js
  src/redux/Reducer/simulation.js
  src/redux/Reducer/unAssignButToRoute.js
  src/routes/route.js
Labels: wip, waiting for reviews
